[2022-11-03 18:16:39,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:39,109] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:39,111] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:39,112] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-03 18:16:39,113] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:39,122] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-11-02 00:00:00+00:00
[2022-11-03 18:16:39,129] {standard_task_runner.py:52} INFO - Started process 68988 to run task
[2022-11-03 18:16:39,132] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpyxgg7v1o', '--error-file', '/tmp/tmp9tne8p3w']
[2022-11-03 18:16:39,134] {standard_task_runner.py:80} INFO - Job 17: Subtask store_user
[2022-11-03 18:16:39,180] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user scheduled__2022-11-02T00:00:00+00:00 [running]> on host 601dc51f5629
[2022-11-03 18:16:39,230] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2022-11-03 18:16:39,233] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-11-03 18:16:39,248] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-11-03 18:16:39,256] {python.py:173} INFO - Done. Returned value was: None
[2022-11-03 18:16:39,266] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20221102T000000, start_date=20221103T181639, end_date=20221103T181639
[2022-11-03 18:16:39,309] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-03 18:16:39,335] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
